minigames:
  games:
    sumo:
      rewards:
        - "time set day"
    redrover:
      allow-runners-to-hit-each-other: true
      killer-rewards: #The rewards the killers will get
        - "time set day"
      runner-rewards: #The rewards the runners will get
        - "time set day"
    spleef:
      allow-players-to-hit-each-other: true #Can players hit each other in the event
      rewards:
        - "time set day"
    lms:
      rewards: #A set commands that will happened when the player wins the event
        - "time set day"
      max-play-time: 1 #Time in minutes untill the game ends if there isn't one man standing
      heal-on-kill: 20 #The amount of hp a player will get when he kill another player
      on-kill-commands: #A set of commands that will happened to a player when he kills another player. use %player% as a place holder.
        - "time set night"

